### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by exiquio** [myAmericaDevSummit2015/RecCollector#15]
I keep seeing errors like the following:

```
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.writeHead (_http_server.js:195:21)
    at returnResult (/Users/thinkmachine/Code/IBM/RecCollector/node_modules/connect-rest/lib/connect-rest.js:166:7)
    at /Users/thinkmachine/Code/IBM/RecCollector/node_modules/connect-rest/lib/connect-rest.js:222:6
    at /Users/thinkmachine/Code/IBM/RecCollector/node_modules/connect-rest/lib/route.js:15:4
    at Object.callback (/Users/thinkmachine/Code/IBM/RecCollector/node_modules/connect-rest/lib/connect-rest.js:113:6)
    at Object.renderResponse [as callback] (/Users/thinkmachine/Code/IBM/RecCollector/app/api/v1/controllers/weather.js:5:23)
    at Object.module.exports.processResponse (/Users/thinkmachine/Code/IBM/RecCollector/app/lib/apiHelper.js:13:17)
    at Request.endpoints.forecast.handleResponse [as _callback] (/Users/thinkmachine/Code/IBM/RecCollector/app/lib/openWeatherMap.js:26:23)
    at Request.self.callback (/Users/thinkmachine/Code/IBM/RecCollector/node_modules/request/request.js:368:22)
```

This should be fixed immediately.

**Comment by exiquio** [comment]
This one is going to be confusing...

**Comment by exiquio** [comment]
https://github.com/myAmericaDevSummit2015/RecCollector/pull/17
